spring.application.name=TpIntegrador

# 1. URL de conexión (cambia 'nombre_de_tu_bd' por el nombre real de tu base de datos)
spring.datasource.url=jdbc:mysql://localhost:3306/tpintegrador?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

# 2. Tu usuario de la base de datos (usualmente 'root')
spring.datasource.username=root

# 3. Tu contraseña de la base de datos
spring.datasource.password=Lucca2005

# 4. Driver de conexión (este es para MySQL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 5. Configuración de Hibernate (esto crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

